export const SEED_MISSIONS = [
  {
    id: 'm_phishing',
    order: 1,
    title: {
      en: 'Phishing Hunter',
      hi: 'फ़िशिंग हंटर',
      ta: 'ஃபிஷிங் வேட்டைக்காரன்',
      te: 'ఫిషింగ్ హంటర్',
      es: 'Cazador de Phishing',
      fr: 'Chasseur de Phishing',
      ar: 'صياد التصيد الاحتيالي',
    },
    category: 'phishing',
    gameType: 'phish_swipe',
    xpReward: 300,
    description: {
      en: 'Swipe through simulated emails and SMS. Identify deceptive links and impostors.',
      hi: 'सिम्युलेटेड ईमेल और एसएमएस की जांच करें। नकली लिंक और धोखेबाजों को पहचानें।',
      ta: 'போலி மின்னஞ்சல்கள் மற்றும் SMS-களை ஆய்வு செய்து அச்சுறுத்தல்களை அடையாளம் காணவும்.',
      te: 'ఈమెయిల్స్ మరియు SMSలలో మోసపూరిత లింకులను గుర్తించండి.',
      es: 'Desliza correos y SMS simulados. Identifica enlaces engañosos e impostores.',
      fr: 'Analysez les e-mails et SMS simulés. Détectez les liens piégés et imposteurs.',
      ar: 'مرر عبر رسائل البريد الإلكتروني والرسائل القصيرة لاكتشاف الروابط المزيفة.',
    },
  },
  {
    id: 'm_scam',
    order: 2,
    title: {
      en: 'Scam Detector',
      hi: 'घोटाला पहचानकर्ता',
      ta: 'மோசடி கண்டறிதல்',
      te: 'స్కామ్ డిటెక్టర్',
      es: 'Detector de Estafas',
      fr: 'Détecteur d\'Arnaques',
      ar: 'كاشف الاحتيال',
    },
    category: 'scam',
    gameType: 'red_flag',
    xpReward: 350,
    description: {
      en: 'Inspect simulated lures and tap suspicious anomalies like fake sender domains and fake urgency.',
      hi: 'संदिग्ध संदेशों की जांच करें और फर्जी डोमेन तथा तात्कालिकता पर टैप करें।',
      ta: 'சந்தேகத்திற்குரிய மின்னஞ்சல்களில் போலி முகவரி மற்றும் அவசர கோரிக்கைகளைத் தொட்டு கண்டறியவும்.',
      te: 'సందేశాలలో ఉన్న లోపాలు మరియు నకిలీ డొమైన్‌లను గుర్తించండి.',
      es: 'Inspecciona mensajes sospechosos y pulsa anomalías como remitentes falsos o urgencia ficticia.',
      fr: 'Inspectez les messages suspects et touchez les anomalies (faux domaines, fausse urgence).',
      ar: 'افحص الرسائل المشبوهة وانقر على الإشارات الحمراء مثل العناوين المزيفة والاستعجال المصطنع.',
    },
  },
  {
    id: 'm_password',
    order: 3,
    title: {
      en: 'Password Guardian',
      hi: 'पासवर्ड रक्षक',
      ta: 'கடவுச்சொல் காவலன்',
      te: 'పాస్‌వర్డ్ గార్డియన్',
      es: 'Guardián de Contraseñas',
      fr: 'Gardien de Mots de Passe',
      ar: 'حارس كلمات المرور',
    },
    category: 'password',
    gameType: 'password_builder',
    xpReward: 400,
    description: {
      en: 'Construct simulated cryptographic blocks and observe live brute-force cracking resistance.',
      hi: 'सुरक्षित सिमुलेटेड पासवर्ड बनाएं और ब्रूट-फोर्स क्रैकिंग समय देखें।',
      ta: 'பாதுகாப்பான கடவுச்சொற்களை உருவாக்கி அவற்றை உடைக்க ஆகும் நேரத்தைப் பகுப்பாய்வு செய்யவும்.',
      te: 'బలమైన పాస్‌వర్డ్‌లను నిర్మించి వాటి రక్షణ సామర్థ్యాన్ని పరీక్షించండి.',
      es: 'Construye bloques criptográficos simulados y observa la resistencia al descifrado por fuerza bruta.',
      fr: 'Assemblez des blocs cryptographiques simulés et évaluez la résistance au cassage par force brute.',
      ar: 'ابنِ كتل تشفير محصنة وراقب مقاومة الكسر والتخمين الفوري.',
    },
  },
  {
    id: 'm_privacy',
    order: 4,
    title: {
      en: 'Privacy Shield',
      hi: 'गोपनीयता ढाल',
      ta: 'தனியுரிமைக் கேடயம்',
      te: 'ప్రైవసీ షీల్డ్',
      es: 'Escudo de Privacidad',
      fr: 'Bouclier de Confidentialité',
      ar: 'درع الخصوصية',
    },
    category: 'privacy',
    gameType: 'phish_swipe',
    xpReward: 450,
    description: {
      en: 'Evaluate app permissions, tracking telemetry, and public Wi-Fi exposure traps.',
      hi: 'ऐप अनुमतियों, डेटा ट्रैकिंग और सार्वजनिक वाई-फ़ाई खतरों का मूल्यांकन करें।',
      ta: 'செயலி அனுமதிகள் மற்றும் பொது வைஃபை ஆபத்துகளை ஆராயுங்கள்.',
      te: 'యాప్ అనుమతులు మరియు పబ్లిక్ వైఫై ప్రమాదాలను అంచనా వేయండి.',
      es: 'Evalúa permisos de aplicaciones, rastreo de datos y trampas en redes Wi-Fi públicas.',
      fr: 'Évaluez les autorisations d\'applications, le traçage et les risques du Wi-Fi public.',
      ar: 'قيّم أذونات التطبيقات ومخاطر شبكات الواي فاي العامة وتعقب البيانات.',
    },
  },
  {
    id: 'm_social',
    order: 5,
    title: {
      en: 'Social Engineering Defense',
      hi: 'सोशल इंजीनियरिंग रक्षा',
      ta: 'சமூகப் பொறியியல் பாதுகாப்பு',
      te: 'సోషల్ ఇంజనీరింగ్ రక్షణ',
      es: 'Defensa de Ingeniería Social',
      fr: 'Défense Ingénierie Sociale',
      ar: 'الدفاع ضد الهندسة الاجتماعية',
    },
    category: 'social_engineering',
    gameType: 'scam_chat',
    xpReward: 500,
    description: {
      en: 'Defend against executive impersonation, urgent OTP pressure, and fake IT support phone calls.',
      hi: 'नकली अधिकारियों, तत्काल ओटीपी दबाव और फर्जी तकनीकी सहायता से अपना बचाव करें।',
      ta: 'அதிகாரிகள் போல் நடிப்பவர்கள் மற்றும் அவசர OTP மோசடிகளிலிருந்து தற்காத்துக் கொள்ளுங்கள்.',
      te: 'నకిలీ అధికారులు మరియు అత్యవసర OTP అభ్యర్థనల నుండి రక్షించుకోండి.',
      es: 'Protégete de la suplantación de identidad ejecutiva, presión por OTPs y falso soporte técnico.',
      fr: 'Défendez-vous contre l\'usurpation d\'identité de dirigeants, la pression pour obtenir des OTP et le faux support IT.',
      ar: 'تصدى لمحاولات انتحال شخصية المدراء والضغط لطلب رموز التحقق والدعم الفني المزيف.',
    },
  },
];

export const SEED_CHALLENGES = [
  // 1. PHISHING (Cards for Phish or Legit swipe game)
  {
    id: 'ch_phish_1',
    missionId: 'm_phishing',
    category: 'phishing',
    type: 'phish_swipe',
    difficulty: 'easy',
    title: {
      en: 'Bank Verification Notice',
      hi: 'बैंक सत्यापन सूचना',
      ta: 'வங்கி சரிபார்ப்பு அறிவிப்பு',
      te: 'బ్యాంక్ ధృవీకరణ నోటీసు',
      es: 'Aviso de Verificación Bancaria',
      fr: 'Avis de Vérification Bancaire',
      ar: 'إشعار التحقق من الحساب البنكي',
    },
    scenario: {
      channel: 'email',
      sender: 'security-alert@bank-verify-account99.com',
      displaySender: 'Secure Banking Alert',
      subject: 'URGENT: Your bank debit card is suspended within 2 hours',
      body: 'Dear Customer, Suspicious login detected from Moscow. Click http://bank-verify-account99.com/secure to confirm your PIN and card CVV immediately.',
      badgeText: 'Urgent Email',
    },
    correctAnswer: false, // Threat (Left)
    explanation: {
      en: 'Suspicious domain name (bank-verify-account99.com) and requests for card CVV/PIN via HTTP link. Legitimate banks never ask for PIN or CVV via email.',
      hi: 'संदिग्ध डोमेन (bank-verify-account99.com) और कार्ड CVV/PIN की मांग। बैंक कभी ईमेल में पिन नहीं मांगते।',
      ta: 'சந்தேகத்திற்குரிய முகவரி மற்றும் CVV/PIN கேட்பது. உண்மையான வங்கிகள் ஒருபோதும் மின்னஞ்சல் மூலம் PIN கேட்பதில்லை.',
      te: 'అనుమానాస్పద డొమైన్ మరియు పిన్ కోరడం. బ్యాంకులు ఎప్పుడూ ఇమెయిల్ ద్వారా పిన్ అడగవు.',
      es: 'Dominio sospechoso y solicitud de CVV/PIN por HTTP. Los bancos nunca piden PIN ni CVV por correo.',
      fr: 'Nom de domaine frauduleux et demande de code PIN/CVV via HTTP. Les banques ne demandent jamais votre code par e-mail.',
      ar: 'نطاق احتيالي وطلب أرقام سرية عبر رابط غير مشفر. البنوك الرسمية لا تطلب الرمز السري عبر البريد.',
    },
    order: 1,
  },
  {
    id: 'ch_phish_2',
    missionId: 'm_phishing',
    category: 'phishing',
    type: 'phish_swipe',
    difficulty: 'easy',
    title: {
      en: 'Two-Factor Authentication Code',
      hi: 'दो-चरणीय सत्यापन कोड',
      ta: 'இருபடி சரிபார்ப்புக் குறியீடு',
      te: 'టూ-ఫ్యాక్టర్ కోడ్',
      es: 'Código de Doble Factor',
      fr: 'Code de Sécurité 2FA',
      ar: 'رمز التحقق الثنائي',
    },
    scenario: {
      channel: 'sms',
      sender: 'GOOG-AUTH',
      displaySender: 'Google Security',
      subject: 'Standard Verification',
      body: '249812 is your Google verification code. Never share this code with anyone. We will never call to request it.',
      badgeText: 'Official SMS',
    },
    correctAnswer: true, // Safe (Right)
    explanation: {
      en: 'Legitimate 2FA notification sent to you during login. It contains no links, explicitly advises never sharing the code, and comes from verified shortcode.',
      hi: 'प्रामाणिक 2FA सूचना। इसमें कोई लिंक नहीं है और कोड साझा न करने की चेतावनी दी गई है।',
      ta: 'உண்மையான 2FA அறிவிப்பு. இதில் எந்த இணைப்பும் இல்லை, குறியீட்டைப் பகிர வேண்டாம் என்று கூறுகிறது.',
      te: 'నిజమైన 2FA కోడ్. ఇందులో ఎటువంటి లింక్ లేదు మరియు కోడ్‌ను పంచుకోవద్దని చెబుతుంది.',
      es: 'Notificación legítima de 2FA. No incluye enlaces y advierte no compartir el código con nadie.',
      fr: 'Notification 2FA authentique. Ne contient aucun lien et rappelle de ne jamais partager le code.',
      ar: 'إشعار تحقق ثنائي رسمي لا يحتوي على أي روابط ويحذر صراحة من مشاركة الرمز.',
    },
    order: 2,
  },
  {
    id: 'ch_phish_3',
    missionId: 'm_phishing',
    category: 'phishing',
    type: 'phish_swipe',
    difficulty: 'medium',
    title: {
      en: 'Package Delivery Fee',
      hi: 'पार्सल वितरण शुल्क',
      ta: 'பார்சல் விநியோக கட்டணம்',
      te: 'పార్శిల్ డెలివరీ ఫీజు',
      es: 'Tasa de Entrega de Paquete',
      fr: 'Frais de Livraison Colis',
      ar: 'رسوم تسليم الطرد',
    },
    scenario: {
      channel: 'sms',
      sender: '+1 (800) 412-9981',
      displaySender: 'Global Express Courier',
      subject: 'Customs Hold',
      body: 'Your package #US-88421 is on hold due to an unpaid $1.50 customs fee. Pay at https://track-parcel-dhl-secure.xyz within 12 hours or package is destroyed.',
      badgeText: 'Smishing SMS',
    },
    correctAnswer: false, // Threat (Left)
    explanation: {
      en: 'Classic smishing scam using extreme urgency, a tiny fake fee ($1.50) to steal credit card details, and an untrusted .xyz domain.',
      hi: 'क्लासिक स्मिशिंग घोटाला। क्रेडिट कार्ड विवरण चुराने के लिए तात्कालिकता और फर्जी .xyz डोमेन का उपयोग।',
      ta: 'அட்டைக் குறிப்புகளைத் திருட குறைந்த கட்டணமும் அவசரமும் காட்டும் மோசடி SMS.',
      te: 'క్రెడిట్ కార్డు వివరాలను దొంగిలించడానికి పంపిన నకిలీ డెలివరీ సందేశం.',
      es: 'Estafa clásica de smishing: urgencia extrema, pequeña tarifa para robar tarjetas y dominio dudoso .xyz.',
      fr: 'Arnaque au SMS classique avec urgence artificielle, petit montant pour dérober la carte et faux domaine .xyz.',
      ar: 'رسالة تصيد احتيالي نموذجية تستغل الاستعجال ومبلغاً ضئيلاً لسرقة بيانات البطاقة البنكية.',
    },
    order: 3,
  },
  {
    id: 'ch_phish_4',
    missionId: 'm_phishing',
    category: 'phishing',
    type: 'phish_swipe',
    difficulty: 'medium',
    title: {
      en: 'Cloud Service Invoice Receipt',
      hi: 'क्लाउड सेवा चालान रसीद',
      ta: 'கிளவுட் சேவை ரசீது',
      te: 'క్లౌడ్ సర్వీస్ ఇన్‌వాయిస్',
      es: 'Factura de Servicio Cloud',
      fr: 'Reçu de Facturation Cloud',
      ar: 'فاتورة خدمة سحابية',
    },
    scenario: {
      channel: 'email',
      sender: 'billing@github.com',
      displaySender: 'GitHub Billing',
      subject: 'Receipt for your GitHub Pro Subscription',
      body: 'Hello, your monthly GitHub subscription of $4.00 was successfully processed. You can review your invoice in your account settings at https://github.com/settings/billing.',
      badgeText: 'Receipt Email',
    },
    correctAnswer: true, // Safe (Right)
    explanation: {
      en: 'Legitimate transaction receipt sent from the official domain (@github.com) linking directly to the verified official settings path without urgency traps.',
      hi: 'आधिकारिक डोमेन (@github.com) से वैध रसीद, जिसमें कोई आपातकालीन दबाव नहीं है।',
      ta: 'அதிகாரப்பூர்வ முகவரியிலிருந்து வந்த உண்மையான ரசீது மின்னஞ்சல்.',
      te: 'అధికారిక డొమైన్ నుండి వచ్చిన నిజమైన బిల్లింగ్ సమాచారం.',
      es: 'Recibo oficial del dominio legítimo (@github.com) con enlace a la ruta auténtica de facturación sin presiones.',
      fr: 'Reçu authentique envoyé par le domaine officiel (@github.com) pointant vers les paramètres sans fausse urgence.',
      ar: 'إشعار رسمي من النطاق المعتمد للخدمة يوجه للموقع الأصلي دون أي تهديد أو استعجال.',
    },
    order: 4,
  },
  {
    id: 'ch_phish_5',
    missionId: 'm_phishing',
    category: 'phishing',
    type: 'phish_swipe',
    difficulty: 'hard',
    title: {
      en: 'Executive Payroll Update',
      hi: 'वेतन खाता अपडेट',
      ta: 'சம்பளக் கணக்கு புதுப்பிப்பு',
      te: 'పేరోల్ అప్‌డేట్',
      es: 'Actualización de Nómina',
      fr: 'Mise à jour Fiche de Paie',
      ar: 'تحديث بيانات الرواتب',
    },
    scenario: {
      channel: 'email',
      sender: 'hr-support@company-intranet-portal.work',
      displaySender: 'Human Resources Department',
      subject: 'Mandatory: New tax regulations require payroll re-login',
      body: 'All staff must immediately re-verify their direct deposit account number at our new single sign-on page: http://company-login-portal.work/auth before 5 PM today.',
      badgeText: 'Internal Impersonation',
    },
    correctAnswer: false, // Threat (Left)
    explanation: {
      en: 'Lookalike domain (.work), fake HR urgency, and an unencrypted HTTP link designed to steal employee credentials and reroute salary direct deposits.',
      hi: 'फर्जी डोमेन (.work), नकली एचआर दबाव और कर्मचारियों के लॉगिन विवरण चुराने का प्रयास।',
      ta: 'போலி நிறுவன முகவரி மூலம் ஊழியர்களின் உள்நுழைவுத் தகவல்களைத் திருடும் முயற்சி.',
      te: 'ఉద్యోగుల వివరాలను దొంగిలించడానికి పంపిన నకిలీ హెచ్‌ఆర్ ఇమెయిల్.',
      es: 'Dominio impostor (.work), falsa urgencia de RRHH y enlace HTTP para desviar depósitos de nómina.',
      fr: 'Domaine trompeur (.work), faux prétexte RH et lien HTTP non sécurisé visant à voler vos identifiants.',
      ar: 'نطاق وهمي (.work) وانتحال لصفة إدارة الموارد البشرية لسرقة بيانات الدخول وحساب الراتب.',
    },
    order: 5,
  },

  // 2. SCAM DETECTOR (Red Flag Hunt game - tap suspicious parts)
  {
    id: 'ch_scam_1',
    missionId: 'm_scam',
    category: 'scam',
    type: 'red_flag',
    difficulty: 'easy',
    title: {
      en: 'Cryptocurrency Lottery Award',
      hi: 'क्रिप्टोकरेंसी लॉटरी पुरस्कार',
      ta: 'கிரிப்டோ லாட்டரி பரிசு',
      te: 'క్రిప్టో లాటరీ బహుమతి',
      es: 'Premio de Lotería en Criptomonedas',
      fr: 'Gain de Loterie Crypto',
      ar: 'جائزة يانصيب العملات الرقمية',
    },
    scenario: {
      sender: 'claim-winner@crypto-foundation-giveaway999.info',
      subject: 'Congratulations! You won 2.5 BTC in the Global Blockchain Draw',
      salutation: 'Dear Lucky Citizen,',
      bodyP1: 'You have been randomly selected as our 1st prize recipient of $150,000 USD worth of Bitcoin.',
      bodyP2: 'To claim your prize, transfer an initial $250 gas fee to our smart contract wallet within 24 hours.',
      bodyP3: 'Click here to access your wallet: http://claim-btc-now.ru/download-key.exe',
      signoff: 'Chief Auditor, International Blockchain Prize Commission',
    },
    redFlags: [
      {
        id: 'flag_domain',
        textSnippet: 'claim-winner@crypto-foundation-giveaway999.info',
        explanation: {
          en: 'Suspicious sender domain (.info with random numbers 999).',
          hi: 'संदिग्ध प्रेषक डोमेन (.info और यादृच्छिक संख्या 999)।',
          ta: 'சந்தேகத்திற்குரிய மின்னஞ்சல் முகவரி (.info மற்றும் எண்கள்).',
          te: 'అనుమానాస్పద ఇమెయిల్ డొమైన్.',
          es: 'Dominio de remitente sospechoso con números aleatorios (.info).',
          fr: 'Domaine d\'expéditeur suspect avec chiffres aléatoires (.info).',
          ar: 'نطاق مرسل مشبوه ينتهي بـ .info مع أرقام عشوائية.',
        },
      },
      {
        id: 'flag_advance_fee',
        textSnippet: 'transfer an initial $250 gas fee to our smart contract wallet',
        explanation: {
          en: 'Advance-fee fraud: legitimate lotteries never require you to pay upfront fees to receive winnings.',
          hi: 'अग्रिम शुल्क धोखाधड़ी: वैध लॉटरी में कभी अग्रिम भुगतान नहीं मांगा जाता।',
          ta: 'முன்பண மோசடி: உண்மையான பரிசுகளுக்கு முன்பணம் செலுத்த வேண்டியதில்லை.',
          te: 'ముందస్తు రుసుము మోసం: బహుమతి కోసం ఎప్పుడూ ముందుగా డబ్బులు అడగరు.',
          es: 'Fraude de pago por adelantado: ningún premio legítimo exige pagar antes para cobrar.',
          fr: 'Arnaque aux frais préalables : aucune loterie légitime n\'exige un paiement pour toucher un gain.',
          ar: 'احتيال الدفع المسبق: الجوائز الحقيقية لا تطلب دفع رسوم مسبقة لاستلامها.',
        },
      },
      {
        id: 'flag_malicious_link',
        textSnippet: 'http://claim-btc-now.ru/download-key.exe',
        explanation: {
          en: 'Executable file download (.exe) hosted on an unencrypted Russian domain (.ru). Highly dangerous malware.',
          hi: 'असुरक्षित (.ru) डोमेन से निष्पादन योग्य (.exe) मैलवेयर फ़ाइल डाउनलोड लिंक।',
          ta: 'அபாயகரமான வைரஸ் கோப்பு (.exe) பதிவிறக்க இணைப்பு.',
          te: 'ప్రమాదకరమైన వైరస్ (.exe) ఫైల్ డౌన్‌లోడ్ లింక్.',
          es: 'Descarga de archivo ejecutable (.exe) no cifrado desde un dominio ruso (.ru). Malware directo.',
          fr: 'Téléchargement d\'exécutable (.exe) non sécurisé sur un domaine russe (.ru). Cheval de Troie potentiel.',
          ar: 'رابط لتحميل ملف تنفيذي خبيث (.exe) من نطاق غير مشفر (.ru).',
        },
      },
    ],
    correctAnswer: ['flag_domain', 'flag_advance_fee', 'flag_malicious_link'],
    explanation: {
      en: 'This message displays 3 blatant red flags: a scam domain, an upfront fee demand, and an .exe malware link.',
      hi: 'इस संदेश में 3 स्पष्ट खतरे हैं: फर्जी डोमेन, अग्रिम शुल्क की मांग और .exe मैलवेयर लिंक।',
      ta: 'இதில் 3 முக்கிய ஆபத்துகள் உள்ளன: போலி முகவரி, முன்பணக் கோரிக்கை மற்றும் வைரஸ் இணைப்பு.',
      te: 'ఈ సందేశంలో 3 స్పష్టమైన ప్రమాదాలు ఉన్నాయి.',
      es: 'Este mensaje tiene 3 señales rojas evidentes: dominio falso, cobro previo y enlace a malware ejecutable.',
      fr: 'Ce message cumule 3 signaux d\'alarme majeurs : domaine frauduleux, demande d\'argent et exécutable pirate.',
      ar: 'تحتوي الرسالة على 3 مؤشرات خطر واضحة: نطاق زائف، طلب دفع مسبق، ورابط لملف تنفيذي ضار.',
    },
    order: 1,
  },
  {
    id: 'ch_scam_2',
    missionId: 'm_scam',
    category: 'scam',
    type: 'red_flag',
    difficulty: 'medium',
    title: {
      en: 'Tech Support Virus Warning',
      hi: 'तकनीकी सहायता वायरस चेतावनी',
      ta: 'தொழில்நுட்ப உதவி வைரஸ் எச்சரிக்கை',
      te: 'టెక్ సపోర్ట్ వైరస్ హెచ్చరిక',
      es: 'Alerta de Virus de Soporte Técnico',
      fr: 'Alerte Virus du Support Informatique',
      ar: 'تحذير فيروس من الدعم الفني',
    },
    scenario: {
      sender: 'system-defender-alerts@ms-windows-security-center.tech',
      subject: 'CRITICAL ALERT: Spyware Trojan.Zeus detected on your device',
      salutation: 'Attention Windows User,',
      bodyP1: 'Your personal data, banking logins and photos are currently being copied to an overseas server.',
      bodyP2: 'Do NOT turn off your PC. Call Toll-Free Microsoft Help immediately: +1 (888) 991-HELP.',
      bodyP3: 'Download the remote diagnostics repair tool: http://anydesk-repair-session.xyz',
      signoff: 'Global Security Operations Desk',
    },
    redFlags: [
      {
        id: 'flag_fake_tech_domain',
        textSnippet: 'system-defender-alerts@ms-windows-security-center.tech',
        explanation: {
          en: 'Fake vendor domain (.tech) impersonating Microsoft Windows.',
          hi: 'माइक्रोसॉफ्ट विंडोज का दिखावा करने वाला नकली डोमेन (.tech)।',
          ta: 'மைக்ரோசாஃப்ட் போல் நடிக்கும் போலி இணைய முகவரி (.tech).',
          te: 'మైక్రోసాఫ్ట్ పేరుతో వచ్చిన నకిలీ డొమైన్.',
          es: 'Falso dominio de soporte (.tech) suplantando a Microsoft Windows.',
          fr: 'Faux domaine technique (.tech) usurpant l\'identité de Microsoft Windows.',
          ar: 'نطاق وهمي (.tech) ينتحل صفة شركة مايكروسوفت.',
        },
      },
      {
        id: 'flag_panic_phone',
        textSnippet: 'Call Toll-Free Microsoft Help immediately: +1 (888) 991-HELP',
        explanation: {
          en: 'Panic-inducing phone prompt designed to trap users into a paid fake technician call.',
          hi: 'नकली तकनीशियन कॉल में फंसाने के लिए दिया गया आपातकालीन फोन नंबर।',
          ta: 'பயமுறுத்தி போலி அழைப்புக்குத் தூண்டும் தொலைபேசி எண்.',
          te: 'నకిలీ టెక్నీషియన్‌తో మాట్లాడించేందుకు ఇచ్చిన ఫోన్ నంబర్.',
          es: 'Teléfono de pánico para redirigirte a un centro de llamadas fraudulento.',
          fr: 'Appel d\'urgence conçu pour vous piéger avec un faux technicien au téléphone.',
          ar: 'رقم هاتف يستغل الذعر لدفع الضحية للتواصل مع محتالين يدعون أنهم فنيو صيانة.',
        },
      },
      {
        id: 'flag_remote_access',
        textSnippet: 'http://anydesk-repair-session.xyz',
        explanation: {
          en: 'Link disguised as a repair tool attempting to install remote desktop control software.',
          hi: 'रिमोट डेस्कटॉप एक्सेस सॉफ्टवेयर इंस्टॉल कराने का प्रयास करने वाला लिंक।',
          ta: 'உங்கள் கணினியைக் கட்டுப்படுத்த முயற்சிக்கும் ஆபத்தான இணைப்பு.',
          te: 'మీ కంప్యూటర్‌ను నియంత్రించడానికి రిమోట్ సాఫ్ట్‌వేర్ లింక్.',
          es: 'Enlace malicioso para instalar software de control remoto en tu equipo.',
          fr: 'Lien visant à faire télécharger un outil de prise de contrôle à distance.',
          ar: 'رابط خبيث يهدف إلى تثبيت برمجيات تحكم عن بعد بالكمبيوتر لسرقة البيانات.',
        },
      },
    ],
    correctAnswer: ['flag_fake_tech_domain', 'flag_panic_phone', 'flag_remote_access'],
    explanation: {
      en: 'Typical tech support scam combining a lookalike domain, fake panic phone number, and a remote-access download link.',
      hi: 'विशिष्ट तकनीकी सहायता घोटाला जिसमें फर्जी डोमेन, आपातकालीन नंबर और रिमोट एक्सेस लिंक शामिल हैं।',
      ta: 'போலி முகவரி, போலி எண் மற்றும் கணினியைக் கட்டுப்படுத்தும் இணைப்பு கொண்ட மோசடி.',
      te: 'టెక్ సపోర్ట్ పేరుతో జరిగే సాధారణ మోసం.',
      es: 'Clásica estafa de soporte técnico: dominio falso, teléfono de pánico y software de acceso remoto.',
      fr: 'Arnaque au faux support classique combinant usurpation, numéro d\'urgence et prise de contrôle.',
      ar: 'احتيال دعم فني نمطي يعتمد على زرع الخوف لفرض الاتصال برقم مريب وتحميل برامج تجسس.',
    },
    order: 2,
  },

  // 3. PASSWORD FORTRESS (Password Builder & Crack Resistance Game)
  {
    id: 'ch_pass_1',
    missionId: 'm_password',
    category: 'password',
    type: 'password_builder',
    difficulty: 'easy',
    title: {
      en: 'Entropy & Special Symbols',
      hi: 'एन्ट्रॉपी और विशेष वर्ण',
      ta: 'என்ட்ரோபி மற்றும் குறியீடுகள்',
      te: 'ఎంట్రోపీ మరియు చిహ్నాలు',
      es: 'Entropía y Caracteres Especiales',
      fr: 'Entropie et Caractères Spéciaux',
      ar: 'الإنتروبيا والرموز الخاصة',
    },
    scenario: {
      targetStrength: 'strong',
      minBlocks: 4,
      instruction: {
        en: 'Assemble a password defense that resists brute force for over 100 years without using easily guessed dictionary terms.',
        hi: 'एक ऐसा पासवर्ड बनाएं जो शब्दकोश के शब्दों के बिना 100 से अधिक वर्षों तक क्रैक न हो सके।',
        ta: 'எளிதில் யூகிக்க முடியாத மற்றும் பல ஆண்டுகள் தாக்குப்பிடிக்கும் வலுவான கடவுச்சொல்லை உருவாக்கவும்.',
        te: '100 సంవత్సరాల వరకు క్రాక్ చేయలేని బలమైన పాస్‌వర్డ్‌ను నిర్మించండి.',
        es: 'Ensambla una contraseña que resista ataques por fuerza bruta por más de 100 años sin palabras comunes.',
        fr: 'Composez un mot de passe résistant à la force brute pendant plus de 100 ans sans mots prévisibles.',
        ar: 'ركب كلمة مرور تقاوم التخمين لأكثر من 100 عام دون استخدام كلمات قاموس شائعة.',
      },
    },
    correctAnswer: { minEntropy: 60, minLength: 14, hasSpecial: true, hasNumbers: true },
    explanation: {
      en: 'Passwords exceeding 14 characters with random symbols and non-dictionary sequences require centuries for GPUs to brute-force.',
      hi: '14 से अधिक वर्णों वाले जटिल पासवर्ड को आधुनिक जीपीयू से भी क्रैक करने में सदियों लग जाते हैं।',
      ta: '14 எழுத்துக்களுக்கு மேல் மற்றும் குறியீடுகள் கொண்ட கடவுச்சொற்களை உடைக்க பல நூற்றாண்டுகள் தேவைப்படும்.',
      te: '14 కంటే ఎక్కువ అక్షరాలు మరియు ప్రత్యేక చిహ్నాలు ఉన్న పాస్‌వర్డ్ అత్యంత సురక్షితమైనది.',
      es: 'Las contraseñas de más de 14 caracteres con símbolos y números requieren siglos para romperse.',
      fr: 'Les mots de passe de plus de 14 caractères combinant symboles et chiffres résistent des siècles.',
      ar: 'كلمات المرور التي تتجاوز 14 رمزاً مع مزيج من الأرقام والرموز تحتاج قروناً طويلة لتخمينها.',
    },
    order: 1,
  },

  // 4. PRIVACY SHIELD
  {
    id: 'ch_priv_1',
    missionId: 'm_privacy',
    category: 'privacy',
    type: 'phish_swipe',
    difficulty: 'medium',
    title: {
      en: 'Flashlight App Permissions Request',
      hi: 'टॉर्च ऐप अनुमति अनुरोध',
      ta: 'டார்ச் செயலி அனுமதி கோரிக்கை',
      te: 'టార్చ్ యాప్ పర్మిషన్ అభ్యర్థన',
      es: 'Permisos de Aplicación Linterna',
      fr: 'Demande d\'Autorisations Application Torche',
      ar: 'طلب أذونات تطبيق المصباح اليدوي',
    },
    scenario: {
      channel: 'mobile_permission',
      sender: 'Super Bright LED Flashlight Free',
      displaySender: 'App Store Download',
      subject: 'Permission Dialogue',
      body: 'Flashlight Pro requests: Read Contacts, Access Precise GPS Location, Record Audio in Background, and Read SMS Messages.',
      badgeText: 'Permission Audit',
    },
    correctAnswer: false, // Threat (Left)
    explanation: {
      en: 'Severe over-permissioning risk. A simple flashlight requires only camera/flash hardware access, never contacts, GPS, microphone or SMS.',
      hi: 'गंभीर गोपनीयता जोखिम। एक साधारण टॉर्च ऐप को केवल कैमरे के फ्लैश की आवश्यकता होती है, संपर्कों या माइक्रोफ़ोन की नहीं।',
      ta: 'கடுமையான தனியுரிமை ஆபத்து. டார்ச் பயன்பாட்டிற்கு கேமரா ஃபிளாஷ் மட்டுமே போதுமானது, தொடர்புகள் அல்லது இருப்பிடம் தேவையில்லை.',
      te: 'తీవ్రమైన ప్రైవసీ ప్రమాదం. టార్చ్ యాప్‌కు కేవలం కెమెరా ఫ్లాష్ అనుమతి సరిపోతుంది.',
      es: 'Riesgo grave de invasión de privacidad. Una linterna solo necesita el hardware del flash, jamás contactos, GPS o micrófono.',
      fr: 'Excès critique d\'autorisations. Une simple lampe de poche n\'a besoin que du flash, jamais de vos contacts, GPS ou micro.',
      ar: 'انتهاك صريح للخصوصية. تطبيق المصباح يحتاج فقط لفلاش الكاميرا ولا مبرر للوصول لجهات الاتصال أو الموقع.',
    },
    order: 1,
  },

  // 5. SOCIAL ENGINEERING (Scam Chat dialog)
  {
    id: 'ch_social_1',
    missionId: 'm_social',
    category: 'social_engineering',
    type: 'scam_chat',
    difficulty: 'hard',
    title: {
      en: 'Urgent CEO Wire Transfer Request',
      hi: 'सीईओ का तत्काल वायर ट्रांसफर अनुरोध',
      ta: 'தலைமை அதிகாரியின் அவசர பணப் பரிமாற்றக் கோரிக்கை',
      te: 'సీఈవో నుండి అత్యవసర నగదు బదిలీ',
      es: 'Transferencia Urgente del Director Ejecutivo',
      fr: 'Demande de Virement Urgent du PDG',
      ar: 'طلب تحويل مالي عاجل من المدير التنفيذي',
    },
    scenario: {
      attackerName: 'Richard Vance (CEO)',
      avatar: 'ceo',
      dialogue: [
        {
          sender: 'attacker',
          message: 'Hey, I am currently locked in a confidential board acquisition meeting and cannot take calls. Are you at your desk?',
        },
        {
          sender: 'attacker',
          message: 'I urgently need you to purchase 10 Apple Gift Cards ($500 each) for client bonuses right now, scratch off the PINs and photo them to me here. It is critical for the meeting.',
        },
      ],
      options: [
        {
          id: 'opt_comply',
          text: 'Sure, Mr. Vance! Headed to the store right away.',
          isThreat: true,
        },
        {
          id: 'opt_verify',
          text: 'I cannot process gift cards or transfers without secondary voice verification via our internal registered phone directory.',
          isThreat: false,
        },
        {
          id: 'opt_ask_details',
          text: 'Send me the project accounting code and I will charge the company credit card.',
          isThreat: true,
        },
      ],
    },
    correctAnswer: 'opt_verify',
    explanation: {
      en: 'Classic Business Email Compromise (BEC) and gift card fraud. Attackers use CEO authority, fake meetings, and secrecy to bypass standard financial controls.',
      hi: 'सीईओ धोखाधड़ी का क्लासिक मामला। वित्तीय नियंत्रण को दरकिनार करने के लिए गोपनीयता और अधिकार का दुरुपयोग।',
      ta: 'நிறுவன அதிகாரிகள் போல் நடித்து பரிசு அட்டைகள் மூலம் பணத்தைத் திருடும் மோசடி.',
      te: 'సీఈవో పేరుతో చేసే సాధారణ కార్పొరేట్ మోసం.',
      es: 'Clásico fraude de compromiso de email corporativo (BEC). Usan la autoridad del director y el secreto para burlar controles.',
      fr: 'Fraude au président classique. Les cybercriminels invoquent l\'autorité et le secret pour contourner les procédures.',
      ar: 'احتيال البريد الإلكتروني للمدير التنفيذي (BEC). يستغل المحتالون السرية لتعطيل الإجراءات المالية المعتمدة.',
    },
    order: 1,
  },
];
